// Copyright 2024 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef IREE_COMPILER_DIALECT_MIPS_TRANSFORMS_PASSES_H_
#define IREE_COMPILER_DIALECT_MIPS_TRANSFORMS_PASSES_H_

#include "mlir/Pass/Pass.h"

namespace mlir::iree_compiler::IREE::MIPS {

//===----------------------------------------------------------------------===//
// Pass factory functions (generated by tablegen + implemented in Passes.cpp)
//===----------------------------------------------------------------------===//

/// Creates the pass that lowers memref-form mips.matmul to
/// func.call @my_matmul_kernel.
std::unique_ptr<mlir::Pass> createLowerMIPSToFuncCallPass();

/// Registers all MIPS passes with the global pass registry so they can be
/// invoked from the command line (e.g. `iree-opt --iree-mips-lower-to-func-call`).
void registerMIPSPasses();

} // namespace mlir::iree_compiler::IREE::MIPS

// clang-format off
#define GEN_PASS_DECL
#include "iree/compiler/Dialect/MIPS/Transforms/Passes.h.inc" // IWYU pragma: keep
// clang-format on

#endif // IREE_COMPILER_DIALECT_MIPS_TRANSFORMS_PASSES_H_
