#!/usr/bin/env python3
# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
"""Emits a header carrying a hash of the plugin API's header surface.

The API version integer covers IreeCompilerPluginInfo alone, so a plugin built
against a changed Client.h loads and then misbehaves. A plugin reports the hash
of the headers it compiled against and is refused when they differ.

The caller names the headers. It covers IREE's own plugin surface, not the
llvm/mlir headers behind it: a plugin has to be built from the same tree for
those to agree, and the symbol rename is what enforces that.
"""

import argparse
import hashlib
import pathlib

_GUARD = "IREE_COMPILER_PLUGINAPI_PLUGINABIHASH_H_"


def compute_hash(paths: list[str]) -> str:
    """Returns the hash of the given headers, independent of argument order."""
    digest = hashlib.sha256()
    for path in sorted(paths, key=lambda p: pathlib.PurePath(p).name):
        # The name is hashed too, so moving content between headers registers.
        digest.update(pathlib.PurePath(path).name.encode())
        digest.update(pathlib.Path(path).read_bytes())
    return digest.hexdigest()[:16]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", action="append", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "// Generated by build_tools/scripts/gen_plugin_abi_hash.py.\n"
        f"#ifndef {_GUARD}\n"
        f"#define {_GUARD}\n"
        "\n"
        f'#define IREE_COMPILER_PLUGIN_ABI_HASH "{compute_hash(args.input)}"\n'
        "\n"
        f"#endif // {_GUARD}\n"
    )


if __name__ == "__main__":
    main()
