// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "iree/tooling/profile/help.h"

static const char kIreeProfileUsage[] =
    "Inspects IREE HAL profile bundles.\n"
    "\n"
    "A .ireeprof bundle is a HAL-native profiling artifact. It contains\n"
    "session metadata, physical-device and queue metadata, executable/export\n"
    "metadata, command-buffer metadata and operations, clock-correlation\n"
    "samples, host queue-operation events, device-timestamped dispatch "
    "events,\n"
    "optional memory lifecycle events, and optional hardware counter samples. "
    "The projection commands below let you enter "
    "from\n"
    "the object you care about and then cross-reference ids in JSONL.\n"
    "\n"
    "Usage:\n"
    "  iree-profile summary [--format=text|jsonl] <file.ireeprof>\n"
    "  iree-profile att [--format=text|jsonl] [--filter=pattern]\n"
    "      [--id=trace_or_dispatch_event_id]\n"
    "      [--rocm_library_path=/opt/rocm/lib] <file.ireeprof>\n"
    "  iree-profile explain [--format=text|jsonl] [--filter=pattern]\n"
    "      [--id=dispatch_event_id] <file.ireeprof>\n"
    "  iree-profile executable [--format=text|jsonl] [--id=executable_id]\n"
    "      [--filter=pattern] [--dispatch_events] <file.ireeprof>\n"
    "  iree-profile dispatch [--format=text|jsonl] [--id=event_id]\n"
    "      [--filter=pattern] [--dispatch_events] <file.ireeprof>\n"
    "  iree-profile command [--format=text|jsonl] [--id=command_buffer_id]\n"
    "      [--filter=pattern] [--dispatch_events] <file.ireeprof>\n"
    "  iree-profile counter [--format=text|jsonl] "
    "[--id=sample_or_related_id]\n"
    "      [--filter=pattern] [--counter_samples] <file.ireeprof>\n"
    "  iree-profile memory [--format=text|jsonl] "
    "[--id=event_or_allocation_id]\n"
    "      [--filter=event_type_pattern] <file.ireeprof>\n"
    "  iree-profile queue [--format=text|jsonl] [--id=submission_id]\n"
    "      [--filter=pattern] [--dispatch_events] <file.ireeprof>\n"
    "  iree-profile export --format=ireeperf-jsonl [--output=path|-]\n"
    "      <file.ireeprof>\n"
    "  iree-profile cat [--format=text|jsonl] <file.ireeprof>\n"
    "  iree-profile --agents_md\n"
    "\n"
    "Commands:\n"
    "  summary      Bundle health, metadata counts, clock fit, and per-device\n"
    "               dispatch timing totals.\n"
    "  att          Decodes AMDGPU ATT/SQTT executable traces using ROCm's\n"
    "               trace decoder and annotates decoded PCs with embedded\n"
    "               code-object disassembly.\n"
    "  explain      Opinionated bottleneck summary: device spans, queue busy\n"
    "               intervals, top exports/dispatches, transfer/memory totals,"
    "\n"
    "               and evidence-backed hints.\n"
    "  executable   Executable/export catalog joined with dispatch timing. "
    "Use\n"
    "               this when optimizing a specific kernel name or export. "
    "Includes\n"
    "               code_object_hash and pipeline_hash when producers provide "
    "them.\n"
    "  dispatch     Per-export dispatch timing aggregates, or individual "
    "events\n"
    "               with --dispatch_events --format=jsonl.\n"
    "  command      Recorded command-buffer operations, metadata, and "
    "per-execution\n"
    "               dispatch spans. Use this to inspect copy/fill/update/"
    "barrier\n"
    "               structure and drill into dispatch timings.\n"
    "  queue        Queue operation events and dispatch-derived submission "
    "spans.\n"
    "  counter      Hardware counter metadata and sample aggregates joined "
    "to\n"
    "               dispatch/export/command/queue ids. Use "
    "--counter_samples\n"
    "               with JSONL for per-dispatch sample rows.\n"
    "  memory       Memory lifecycle events and high-water summaries for "
    "slabs,\n"
    "               pools, async queue allocations, and HAL buffers. "
    "Live-at-end counts\n"
    "               are capture-window state, not required leaks.\n"
    "  export       Decoded tooling interchange export. The first supported\n"
    "               format is schema-versioned ireeperf-jsonl.\n"
    "  cat          Raw bundle record dump for format archaeology/debugging.\n"
    "\n"
    "Important flags:\n"
    "  --format=text|jsonl     Text for humans, JSONL for tools and agents.\n"
    "  --filter=pattern        Wildcard over dispatch/export keys, command op\n"
    "                          names/keys, or queue/memory event type names,\n"
    "                          such as '*softmax*' or 'copy'.\n"
    "  --id=N                  att: trace_id or dispatch event_id;\n"
    "                          dispatch: event_id; executable: executable_id;\n"
    "                          command: command_buffer_id; memory: "
    "event_id or\n"
    "                          allocation_id; queue: submission_id; "
    "counter:\n"
    "                          sample_id, dispatch_event_id, "
    "submission_id, or\n"
    "                          command_buffer_id; explain:\n"
    "                          dispatch event id.\n"
    "  --dispatch_events       Stream individual dispatch_event rows instead "
    "of\n"
    "                          only aggregate projection rows. Requires "
    "JSONL.\n"
    "  --counter_samples       Stream individual counter_sample rows instead "
    "of\n"
    "                          only aggregate counter rows. Requires JSONL.\n"
    "  --output=path|-         Export destination path, or `-` for stdout.\n"
    "  --rocm_library_path=path ROCm library directory or exact dynamic "
    "library\n"
    "                          path used by `att`. Overrides\n"
    "                          IREE_HAL_AMDGPU_LIBAQLPROFILE_PATH and\n"
    "                          IREE_HAL_AMDGPU_LIBHSA_PATH; if all are "
    "unset,\n"
    "                          uses the system dynamic library search path.\n"
    "  --agents_md             Print a Markdown guide optimized for "
    "AGENTS.md.\n"
    "\n"
    "Capture examples:\n"
    "  iree-benchmark-module --device=amdgpu --module=model.vmfb \\\n"
    "      --function=main --benchmark_min_time=20x \\\n"
    "      --device_profiling_mode=queue \\\n"
    "      --device_profiling_output=/tmp/model.ireeprof\n"
    "\n"
    "Embedding examples:\n"
    "  Use iree_hal_profile_file_sink_create to create a file-backed sink,\n"
    "  set iree_hal_device_profiling_options_t::sink, then call\n"
    "  iree_hal_device_profiling_begin/end around the work to capture.\n"
    "\n"
    "Analysis examples:\n"
    "  iree-profile summary /tmp/model.ireeprof\n"
    "  iree-profile att --rocm_library_path=/opt/rocm/lib \\\n"
    "      --filter='*matmul*' /tmp/model.ireeprof\n"
    "  iree-profile explain /tmp/model.ireeprof\n"
    "  iree-profile explain --format=jsonl /tmp/model.ireeprof | \\\n"
    "      jq 'select(.type | startswith(\"explain_top_\"))'\n"
    "  iree-profile export --format=ireeperf-jsonl \\\n"
    "      --output=/tmp/model.ireeperf.jsonl /tmp/model.ireeprof\n"
    "  iree-profile executable --filter='*matmul*' /tmp/model.ireeprof\n"
    "  iree-profile dispatch --format=jsonl /tmp/model.ireeprof | \\\n"
    "      jq 'select(.type==\"dispatch_group\") | {key,avg_ns,count}'\n"
    "  iree-profile queue --format=jsonl /tmp/model.ireeprof | \\\n"
    "      jq 'select(.type==\"queue_event\" or "
    ".type==\"queue_device_event\" or .type==\"queue_submission\")'\n"
    "  iree-profile counter --format=jsonl /tmp/model.ireeprof | \\\n"
    "      jq 'select(.type==\"counter_group\") | "
    "{key,counter,avg,sum,samples}'\n"
    "  iree-profile counter --format=jsonl --counter_samples \\\n"
    "      /tmp/model.ireeprof | jq 'select(.type==\"counter_sample\")'\n"
    "  iree-profile memory --format=jsonl /tmp/model.ireeprof | \\\n"
    "      jq 'select(.type==\"memory_pool\") | \\\n"
    "          {kind,physical_device_ordinal,pool_id,"
    "high_water_bytes,waits}'\n"
    "  iree-profile command --id=1 --format=jsonl --dispatch_events \\\n"
    "      /tmp/model.ireeprof | jq 'select(.type==\"dispatch_event\")'\n"
    "\n"
    "Use `iree-profile --agents_md` for a Markdown playbook with JSONL record\n"
    "types and cross-reference recipes.\n";

void iree_profile_fprint_usage(FILE* file) {
  fputs("iree-profile\n", file);
  fputs(kIreeProfileUsage, file);
}

void iree_profile_print_agent_markdown(FILE* file) {
  fputs(
      "# IREE HAL Profiling With iree-profile\n"
      "\n"
      "Use `iree-profile` to inspect `.ireeprof` bundles emitted by IREE HAL\n"
      "device profiling. Prefer `--format=jsonl` for automated analysis: each\n"
      "line is one independent JSON record that can be filtered with `jq`.\n"
      "\n"
      "## Capture\n"
      "\n"
      "Capture from `iree-benchmark-module` with HAL queue profiling "
      "enabled:\n"
      "\n"
      "```bash\n"
      "iree-benchmark-module --device=amdgpu --module=model.vmfb \\\n"
      "  --function=main --benchmark_min_time=20x \\\n"
      "  --device_profiling_mode=queue \\\n"
      "  --device_profiling_output=/tmp/model.ireeprof\n"
      "```\n"
      "\n"
      "Embedding applications can capture the same bundle through the HAL "
      "API:\n"
      "\n"
      "```c\n"
      "iree_io_file_handle_t* file_handle = NULL;\n"
      "iree_hal_profile_sink_t* sink = NULL;\n"
      "IREE_RETURN_IF_ERROR(iree_io_file_handle_create(\n"
      "    IREE_IO_FILE_MODE_WRITE | IREE_IO_FILE_MODE_SEQUENTIAL_SCAN,\n"
      "    IREE_SV(\"/tmp/model.ireeprof\"), 0, host_allocator, "
      "&file_handle));\n"
      "IREE_RETURN_IF_ERROR(iree_hal_profile_file_sink_create(\n"
      "    file_handle, host_allocator, &sink));\n"
      "iree_hal_device_profiling_options_t options = {0};\n"
      "options.mode = IREE_HAL_DEVICE_PROFILING_MODE_QUEUE_OPERATIONS;\n"
      "options.sink = sink;\n"
      "IREE_RETURN_IF_ERROR(iree_hal_device_profiling_begin(device, "
      "&options));\n"
      "/* Run workload. */\n"
      "IREE_RETURN_IF_ERROR(iree_hal_device_profiling_end(device));\n"
      "iree_hal_profile_sink_release(sink);\n"
      "iree_io_file_handle_release(file_handle);\n"
      "```\n"
      "\n"
      "## Commands\n"
      "\n"
      "- `summary` checks bundle health, metadata counts, dispatch counts, "
      "clock\n"
      "  correlation, and per-device timing totals.\n"
      "- `att` decodes AMDGPU ATT/SQTT executable trace blobs with ROCm's\n"
      "  trace decoder and annotates decoded PCs using code objects embedded "
      "in\n"
      "  the `.ireeprof` bundle. Library lookup uses `--rocm_library_path` "
      "first,\n"
      "  then `IREE_HAL_AMDGPU_LIBAQLPROFILE_PATH`, then "
      "`IREE_HAL_AMDGPU_LIBHSA_PATH`,\n"
      "  then the normal system dynamic library search path.\n"
      "- `explain` gives an opinionated first-pass bottleneck view: visible "
      "device\n"
      "  spans, summed active dispatch time, merged per-queue busy intervals, "
      "top\n"
      "  exports, top individual dispatches, transfer totals, memory "
      "pressure,\n"
      "  and evidence-backed hints. Queue gap hints require queue event "
      "records;\n"
      "  do not infer queue dependency causes from dispatch record order.\n"
      "- `executable` lists executable/export metadata and joins export ids "
      "to\n"
      "  dispatch timing aggregates. Hash-capable producers include "
      "`code_object_hash`\n"
      "  on `executable` rows and `pipeline_hash` on `executable_export` "
      "rows for\n"
      "  cross-run and external-tool correlation.\n"
      "- `dispatch` groups timings by executable export, or emits every "
      "dispatch\n"
      "  event with `--dispatch_events`.\n"
      "- `command` lists command-buffer metadata, static operation records, "
      "and\n"
      "  execution spans grouped by `command_buffer_id` and `submission_id`.\n"
      "- `queue` groups dispatch-derived queue submissions by physical queue "
      "and\n"
      "  `submission_id`, and emits host queue-operation events when the "
      "producer\n"
      "  provides them. Queue events include operation type, wait/signal "
      "counts,\n"
      "  dependency strategy, payload bytes, and related object ids. "
      "Queue-device\n"
      "  events add raw device start/end ticks for timed submissions such as "
      "alloca,\n"
      "  execute, and dealloca.\n"
      "- `counter` joins hardware counter metadata and samples to "
      "dispatch/export,\n"
      "  command-buffer, queue, and submission ids. Aggregate mode emits "
      "per-counter\n"
      "  statistics; `--counter_samples --format=jsonl` emits every matched "
      "sample\n"
      "  row with raw values for drilldown.\n"
      "- `memory` summarizes slab/provider events, pool reservation events, "
      "async\n"
      "  queue alloca/dealloca, and synchronous HAL buffer allocation/free "
      "high-water behavior. With `--format=jsonl` it emits individual\n"
      "  `memory_event` rows before the summary and then emits `memory_pool` "
      "and\n"
      "  `memory_allocation` rows for pool/provider and lifecycle drilldown. "
      "Live\n"
      "  allocations at profile end are capture-window state and may be "
      "normal\n"
      "  for retained outputs or embedding-managed buffers.\n"
      "- `export --format=ireeperf-jsonl` decodes `.ireeprof` into a "
      "schema-versioned\n"
      "  tooling interchange stream. This is the stable boundary for jq, "
      "agents,\n"
      "  telemetry upload, and optional Python adapters such as Perfetto or "
      "SQLite.\n"
      "- `cat` dumps raw bundle records and is mainly for format debugging.\n"
      "\n"
      "## JSONL Record Types\n"
      "\n"
      "- `summary` emits `summary` and `device_summary`.\n"
      "- `att --format=jsonl` emits `att_trace` and `att_instruction`.\n"
      "- `explain --format=jsonl` emits `explain_summary`, "
      "`explain_device`,\n"
      "  `explain_queue`, `explain_top_export`, "
      "`explain_top_dispatch`,\n"
      "  `explain_queue_operations`, `explain_memory_pressure`, and "
      "`explain_hint`.\n"
      "- `executable --format=jsonl` emits `executable_summary`, "
      "`executable`,\n"
      "  `executable_export`, and `executable_export_dispatch_group`.\n"
      "- `dispatch --format=jsonl` emits `dispatch_summary` and "
      "`dispatch_group`.\n"
      "- `dispatch --format=jsonl --dispatch_events` emits `dispatch_event` "
      "rows\n"
      "  followed by `dispatch_summary`.\n"
      "- `command --format=jsonl` emits `command_summary`, `command_buffer`,\n"
      "  `command_operation`, and `command_execution`.\n"
      "- `queue --format=jsonl` emits `queue_summary`, `queue`,\n"
      "  `queue_submission`, `queue_device_event`, and `queue_event`.\n"
      "- `counter --format=jsonl` emits `counter_summary`, `counter_set`,\n"
      "  `counter`, and `counter_group`.\n"
      "- `counter --format=jsonl --counter_samples` additionally emits\n"
      "  `counter_sample` rows before the summary.\n"
      "- `memory --format=jsonl` emits `memory_event`, `memory_summary`,\n"
      "  `memory_device`, `memory_pool`, and `memory_allocation`.\n"
      "- `export --format=ireeperf-jsonl` emits records with "
      "`schema_version`\n"
      "  and `record_type`: `schema`, `session`, `device`, `queue`,\n"
      "  `executable`, `executable_export`, `command_buffer`,\n"
      "  `command_operation`, `clock_correlation`, `dispatch_event`,\n"
      "  `queue_event`, `queue_device_event`, `memory_event`, "
      "`event_relationship`, "
      "`counter_set`,\n"
      "  `counter`, `counter_sample`, and `diagnostic`.\n"
      "\n"
      "## Cross-Reference Keys\n"
      "\n"
      "- `dispatch_event.event_id` uniquely identifies one dispatch event in "
      "the\n"
      "  profile stream. Use `dispatch --id=<event_id>` to isolate it.\n"
      "- `dispatch_event.submission_id` joins dispatches to "
      "`queue_submission`.\n"
      "  Use `queue --id=<submission_id>` or "
      "`queue --id=<submission_id> --dispatch_events` to inspect a "
      "submission.\n"
      "- `dispatch_event.command_buffer_id` joins dispatches to "
      "`command_buffer`\n"
      "  and `command_execution`. Use `command --id=<command_buffer_id>`.\n"
      "- `dispatch_event.command_index` is the ordinal of the dispatch within "
      "the\n"
      "  command buffer when the event came from reusable command-buffer "
      "replay.\n"
      "- `command_operation.command_buffer_id` and "
      "`command_operation.command_index`\n"
      "  join recorded command-buffer operations to dispatch events. "
      "`op` and\n"
      "  `key` can be filtered with `command --filter=<pattern>`.\n"
      "- `dispatch_event.executable_id` plus `dispatch_event.export_ordinal` "
      "joins\n"
      "  to `executable_export`. The `key` field is the export name when "
      "present,\n"
      "  otherwise a stable numeric fallback.\n"
      "- `physical_device_ordinal`, `queue_ordinal`, and `stream_id` identify "
      "the\n"
      "  producing physical queue within the session.\n"
      "- `queue_event.submission_id` joins queue operation metadata to "
      "`queue_submission`\n"
      "  and dispatch events. `queue_event.command_buffer_id` joins execute "
      "events\n"
      "  to `command_buffer`; `queue_event.allocation_id` joins alloca/"
      "dealloca\n"
      "  events to memory events.\n"
      "- `queue_device_event.submission_id` joins host queue operations to "
      "device\n"
      "  start/end ticks in the same submission. For reusable command-buffer "
      "execute,\n"
      "  `queue_device_event.command_buffer_id` identifies the command buffer "
      "whose\n"
      "  whole-submission device span encloses its dispatch events.\n"
      "- `counter_sample.sample_id` identifies one producer sample. "
      "`counter_sample.dispatch_event_id`, `submission_id`, "
      "`command_buffer_id`,\n"
      "  `command_index`, `executable_id`, `export_ordinal`, "
      "`physical_device_ordinal`,\n"
      "  `queue_ordinal`, and `stream_id` join counter data to the matching\n"
      "  dispatch, command, executable, and queue projections. "
      "`counter_set_id`\n"
      "  plus `counter_ordinal` joins samples to counter metadata.\n"
      "- `memory_event.submission_id` joins queue alloca/dealloca events to "
      "queue\n"
      "  submissions when nonzero. `memory_event.allocation_id` joins all "
      "events\n"
      "  associated with one producer-defined allocation handle. "
      "`memory_pool`\n"
      "  groups by producer pool/provider id and memory type. "
      "`memory_allocation`\n"
      "  groups capture-window lifecycle rows by kind, allocation id, and "
      "pool id.\n"
      "  `memory_device`\n"
      "  live/high-water fields are computed over the capture window, so "
      "they\n"
      "  need not balance to zero if buffers outlive profiling.\n"
      "\n"
      "## Recipes\n"
      "\n"
      "Find the slowest kernel/export groups:\n"
      "\n"
      "```bash\n"
      "iree-profile explain --format=jsonl /tmp/model.ireeprof | \\\n"
      "  jq 'select(.type==\"explain_top_export\") | \\\n"
      "      {rank,key,total_ns,avg_ns,max_ns,dispatches}'\n"
      "```\n"
      "\n"
      "Find the slowest individual dispatches:\n"
      "\n"
      "```bash\n"
      "iree-profile explain --format=jsonl /tmp/model.ireeprof | \\\n"
      "  jq 'select(.type==\"explain_top_dispatch\") | \\\n"
      "      {rank,event_id,submission_id,key,duration_ns}'\n"
      "```\n"
      "\n"
      "Build a full custom export table:\n"
      "\n"
      "```bash\n"
      "iree-profile dispatch --format=jsonl /tmp/model.ireeprof | \\\n"
      "  jq -s 'map(select(.type==\"dispatch_group\")) | \\\n"
      "         sort_by(.total_ns) | reverse[:20] | \\\n"
      "         map({key,count,avg_ns,total_ns,max_ns})'\n"
      "```\n"
      "\n"
      "Export the full decoded interchange stream for downstream tools:\n"
      "\n"
      "```bash\n"
      "iree-profile export --format=ireeperf-jsonl \\\n"
      "  --output=/tmp/model.ireeperf.jsonl /tmp/model.ireeprof\n"
      "jq 'select(.record_type==\"dispatch_event\") | \\\n"
      "    {event_id,key,duration_ns,duration_time_domain,"
      "derived_time_available,derived_time_domain}' \\\n"
      "  /tmp/model.ireeperf.jsonl\n"
      "```\n"
      "\n"
      "Show every dispatch of one kernel name pattern:\n"
      "\n"
      "```bash\n"
      "iree-profile dispatch --format=jsonl --dispatch_events \\\n"
      "  --filter='*softmax*' /tmp/model.ireeprof | \\\n"
      "  jq 'select(.type==\"dispatch_event\") | \\\n"
      "      {event_id,submission_id,command_buffer_id,command_index,key,"
      "duration_ns}'\n"
      "```\n"
      "\n"
      "Decode ATT traces for one kernel name pattern:\n"
      "\n"
      "```bash\n"
      "iree-profile att --format=jsonl --filter='*matmul*' \\\n"
      "  /tmp/model.ireeprof | \\\n"
      "  jq 'select(.type==\"att_instruction\") | \\\n"
      "      {trace_id,pc,category,hits,stall,instruction}'\n"
      "```\n"
      "\n"
      "Find expensive command-buffer executions:\n"
      "\n"
      "```bash\n"
      "iree-profile command --format=jsonl /tmp/model.ireeprof | \\\n"
      "  jq -s 'map(select(.type==\"command_execution\")) | \\\n"
      "         sort_by(.span_ns) | reverse[:20] | \\\n"
      "         map({command_buffer_id,submission_id,span_ns,dispatches})'\n"
      "```\n"
      "\n"
      "Drill into all dispatches for command buffer 1:\n"
      "\n"
      "```bash\n"
      "iree-profile command --id=1 --format=jsonl --dispatch_events \\\n"
      "  /tmp/model.ireeprof | jq 'select(.type==\"dispatch_event\")'\n"
      "```\n"
      "\n"
      "Show the recorded operation stream for command buffer 1:\n"
      "\n"
      "```bash\n"
      "iree-profile command --id=1 --format=jsonl /tmp/model.ireeprof | \\\n"
      "  jq 'select(.type==\"command_operation\") | \\\n"
      "      {command_index,op,key,length,workgroup_count}'\n"
      "```\n"
      "\n"
      "Find queue submissions with long device spans:\n"
      "\n"
      "```bash\n"
      "iree-profile queue --format=jsonl /tmp/model.ireeprof | \\\n"
      "  jq -s 'map(select(.type==\"queue_submission\")) | \\\n"
      "         sort_by(.span_ns) | reverse[:20] | \\\n"
      "         map({submission_id,physical_device_ordinal,queue_ordinal,"
      "span_ns,dispatches})'\n"
      "```\n"
      "\n"
      "Drill from queue submission 4 to its dispatch events:\n"
      "\n"
      "```bash\n"
      "iree-profile queue --id=4 --format=jsonl --dispatch_events \\\n"
      "  /tmp/model.ireeprof | jq 'select(.type==\"dispatch_event\")'\n"
      "```\n"
      "\n"
      "Summarize hardware counters by kernel/export:\n"
      "\n"
      "```bash\n"
      "iree-profile counter --format=jsonl /tmp/model.ireeprof | \\\n"
      "  jq -s 'map(select(.type==\"counter_group\")) | \\\n"
      "         sort_by(.sum) | reverse[:20] | \\\n"
      "         map({key,counter,samples,avg,sum})'\n"
      "```\n"
      "\n"
      "Show raw counter samples for one dispatch event:\n"
      "\n"
      "```bash\n"
      "iree-profile counter --format=jsonl --counter_samples \\\n"
      "  --id=<dispatch_event_id> /tmp/model.ireeprof | \\\n"
      "  jq 'select(.type==\"counter_sample\") | \\\n"
      "      {sample_id,dispatch_event_id,key,counter,value,values}'\n"
      "```\n"
      "\n"
      "Inspect allocation high-water by physical device:\n"
      "\n"
      "```bash\n"
      "iree-profile memory --format=jsonl /tmp/model.ireeprof | \\\n"
      "  jq 'select(.type==\"memory_device\") | \\\n"
      "      {physical_device_ordinal,current_queue_allocations,"
      "high_water_queue_bytes,current_buffer_allocations,"
      "high_water_buffer_bytes}'\n"
      "```\n"
      "\n"
      "Find pools/providers with the largest memory high-water:\n"
      "\n"
      "```bash\n"
      "iree-profile memory --format=jsonl /tmp/model.ireeprof | \\\n"
      "  jq -s 'map(select(.type==\"memory_pool\")) | \\\n"
      "         sort_by(.high_water_bytes) | reverse[:20] | \\\n"
      "         map({kind,physical_device_ordinal,pool_id,memory_type,"
      "high_water_bytes,waits})'\n"
      "```\n"
      "\n"
      "Trace one allocation lifecycle:\n"
      "\n"
      "```bash\n"
      "iree-profile memory --format=jsonl --id=<allocation_id> \\\n"
      "  /tmp/model.ireeprof | \\\n"
      "  jq 'select(.type==\"memory_event\" or "
      ".type==\"memory_allocation\")'\n"
      "```\n"
      "\n"
      "Map executable ids and export ordinals to names:\n"
      "\n"
      "```bash\n"
      "iree-profile executable --format=jsonl /tmp/model.ireeprof | \\\n"
      "  jq 'select(.type==\"executable_export\") | \\\n"
      "      {executable_id,export_ordinal,key,binding_count,workgroup_size}'\n"
      "```\n"
      "\n"
      "## Notes For Agents\n"
      "\n"
      "Treat `summary` as the first sanity check: if clock fitting is "
      "unavailable\n"
      "or dispatch timestamps are invalid, timing conclusions are suspect. "
      "For\n"
      "automated analysis, prefer entering through `queue`, `command`,\n"
      "`executable`, or `dispatch` with JSONL and then drilling into\n"
      "`--dispatch_events` using the ids above. Do not infer queue ordering "
      "from\n"
      "record order alone; HAL queue ordering is established by semaphore "
      "edges,\n"
      "and full queue-edge records require producer support beyond the "
      "current\n"
      "dispatch-derived projections.\n",
      file);
}

const char* iree_profile_usage_text(void) { return kIreeProfileUsage; }
