// RUN: iree-opt %s --split-input-file --mlir-print-local-scope \
// RUN:   --pass-pipeline="builtin.module(func.func(iree-codegen-gpu-distribute-forall, canonicalize, cse))" | FileCheck %s

#translation_info = #iree_codegen.translation_info<pipeline = #iree_gpu.pipeline<TileAndFuse> workgroup_size = [64, 2, 1] subgroup_size = 32>

func.func @distribute_thread_forall(%out : memref<?xi32>)
    attributes {translation_info = #translation_info} {
  %c0 = arith.constant 0 : i32
  scf.forall (%arg0) in (1024) {
    memref.store %c0, %out[%arg0] : memref<?xi32>
  } {mapping = [#gpu.thread<linear_dim_0>]}
  return
}

// CHECK-LABEL: func @distribute_thread_forall
//   CHECK-DAG:   %[[C128:.+]] = arith.constant 128 : index
//   CHECK-DAG:   %[[C0:.+]] = arith.constant 0 : index
//   CHECK-DAG:   %[[C1024:.+]] = arith.constant 1024 : index
//   CHECK-DAG:   %[[TX:.+]] = gpu.thread_id x
//   CHECK-DAG:   %[[TY:.+]] = gpu.thread_id y
//       CHECK:   %[[TFLAT:.+]] = affine.linearize_index disjoint [%[[TY]], %[[TX]]] by (2, 64)
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]
//       CHECK:   scf.for %[[I:.+]] = %[[C0]] to %[[C1024]] step %[[C128]] {
//       CHECK:     %[[LINID:.+]] = affine.apply affine_map<(d0)[s0] -> (d0 + s0)>(%[[I]])[%[[TFLAT]]]
//       CHECK:     memref.store {{.*}}[%[[LINID]]]
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]

// -----

#translation_info = #iree_codegen.translation_info<pipeline = #iree_gpu.pipeline<TileAndFuse> workgroup_size = [64, 2, 1] subgroup_size = 32>

func.func @distribute_warp_forall(%out : memref<?xi32>)
    attributes {translation_info = #translation_info} {
  %c0 = arith.constant 0 : i32
  scf.forall (%arg0) in (32) {
    memref.store %c0, %out[%arg0] : memref<?xi32>
  } {mapping = [#gpu.warp<linear_dim_0>]}
  return
}

// CHECK-LABEL: func @distribute_warp_forall
//   CHECK-DAG:   %[[C4:.+]] = arith.constant 4 : index
//   CHECK-DAG:   %[[C0:.+]] = arith.constant 0 : index
//   CHECK-DAG:   %[[C32:.+]] = arith.constant 32 : index
//   CHECK-DAG:   %[[TX:.+]] = gpu.thread_id x
//   CHECK-DAG:   %[[TY:.+]] = gpu.thread_id y
//       CHECK:   %[[TFLAT:.+]] = affine.linearize_index disjoint [%[[TY]], %[[TX]]] by (2, 64)
//       CHECK:   %[[WARPSPLIT:.+]]:2 = affine.delinearize_index %[[TFLAT]] into (4, 32)
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]
//       CHECK:   scf.for %[[I:.+]] = %[[C0]] to %[[C32]] step %[[C4]] {
//       CHECK:     %[[LINID:.+]] = affine.apply affine_map<(d0)[s0] -> (d0 + s0)>(%[[I]])[%[[WARPSPLIT]]#0]
//       CHECK:     memref.store {{.*}}[%[[LINID]]]
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]

// -----

#translation_info = #iree_codegen.translation_info<pipeline = #iree_gpu.pipeline<TileAndFuse> workgroup_size = [64, 2, 1] subgroup_size = 32>

func.func @distribute_lane_forall(%out : memref<?xi32>)
    attributes {translation_info = #translation_info} {
  scf.forall (%arg0) in (32) {
    %c0 = arith.constant 0 : i32
    memref.store %c0, %out[%arg0] : memref<?xi32>
  } {mapping = [#iree_gpu.lane_id<0>]}
  return
}

// CHECK-LABEL: func @distribute_lane_forall
//       CHECK:   %[[LANEID:.+]] = gpu.lane_id upper_bound 32
//       CHECK:   memref.store {{.*}}[%[[LANEID]]]

// -----

#translation_info = #iree_codegen.translation_info<pipeline = #iree_gpu.pipeline<TileAndFuse> workgroup_size = [64, 2, 1] subgroup_size = 32>

func.func @distribute_thread_forall_drop_for_loop(%out : memref<?xi32>)
    attributes {translation_info = #translation_info} {
  %c0 = arith.constant 0 : i32
  scf.forall (%arg0) in (128) {
    memref.store %c0, %out[%arg0] : memref<?xi32>
  } {mapping = [#gpu.thread<linear_dim_0>]}
  return
}

// CHECK-LABEL: func @distribute_thread_forall_drop_for_loop
//   CHECK-DAG:   %[[TX:.+]] = gpu.thread_id x
//   CHECK-DAG:   %[[TY:.+]] = gpu.thread_id y
//       CHECK:   %[[LINID:.+]] = affine.linearize_index disjoint [%[[TY]], %[[TX]]] by (2, 64)
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]
//       CHECK:   memref.store {{.*}}[%[[LINID]]]
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]

// -----

#translation_info = #iree_codegen.translation_info<pipeline = #iree_gpu.pipeline<TileAndFuse> workgroup_size = [64, 2, 1] subgroup_size = 32>

func.func @distribute_thread_forall_single_thread(%out : memref<?xi32>)
    attributes {translation_info = #translation_info} {
  %c0 = arith.constant 0 : i32
  scf.forall (%arg0) in (1) {
    memref.store %c0, %out[%arg0] : memref<?xi32>
  } {mapping = [#gpu.thread<linear_dim_0>]}
  return
}

// CHECK-LABEL: func @distribute_thread_forall_single_thread
//   CHECK-DAG:   %[[C128:.+]] = arith.constant 128 : index
//   CHECK-DAG:   %[[C1:.+]] = arith.constant 1 : index
//   CHECK-DAG:   %[[TX:.+]] = gpu.thread_id x
//   CHECK-DAG:   %[[TY:.+]] = gpu.thread_id y
//       CHECK:   %[[TFLAT:.+]] = affine.linearize_index disjoint [%[[TY]], %[[TX]]] by (2, 64)
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]
//       CHECK:   scf.for %[[I:.+]] = %[[TFLAT]] to %[[C1]] step %[[C128]] {
//       CHECK:     memref.store {{.*}}[%[[I]]]
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]

// -----

#translation_info = #iree_codegen.translation_info<pipeline = #iree_gpu.pipeline<TileAndFuse> workgroup_size = [64, 2, 1] subgroup_size = 32>

func.func @distribute_thread_forall_overhang(%out : memref<?xi32>)
    attributes {translation_info = #translation_info} {
  %c0 = arith.constant 0 : i32
  scf.forall (%arg0) in (513) {
    memref.store %c0, %out[%arg0] : memref<?xi32>
  } {mapping = [#gpu.thread<linear_dim_0>]}
  return
}

// CHECK-LABEL: func @distribute_thread_forall_overhang
//   CHECK-DAG:   %[[C128:.+]] = arith.constant 128 : index
//   CHECK-DAG:   %[[C513:.+]] = arith.constant 513 : index
//   CHECK-DAG:   %[[TX:.+]] = gpu.thread_id x
//   CHECK-DAG:   %[[TY:.+]] = gpu.thread_id y
//       CHECK:   %[[TFLAT:.+]] = affine.linearize_index disjoint [%[[TY]], %[[TX]]] by (2, 64)
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]
//       CHECK:   scf.for %[[I:.+]] = %[[TFLAT]] to %[[C513]] step %[[C128]] {
//       CHECK:     memref.store {{.*}}[%[[I]]]
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]

// -----

#translation_info = #iree_codegen.translation_info<pipeline = #iree_gpu.pipeline<TileAndFuse> workgroup_size = [64, 2, 1] subgroup_size = 32>

func.func @distribute_thread_forall_multi_dim(%out : memref<?x?x?xi32>)
    attributes {translation_info = #translation_info} {
  %c0 = arith.constant 0 : i32
  scf.forall (%arg0, %arg1, %arg2) in (16, 8, 4) {
    memref.store %c0, %out[%arg0, %arg1, %arg2] : memref<?x?x?xi32>
  } {mapping = [#gpu.thread<linear_dim_2>, #gpu.thread<linear_dim_1>, #gpu.thread<linear_dim_0>]}
  return
}

// CHECK-LABEL: func @distribute_thread_forall_multi_dim
//   CHECK-DAG:   %[[C128:.+]] = arith.constant 128 : index
//   CHECK-DAG:   %[[C512:.+]] = arith.constant 512 : index
//   CHECK-DAG:   %[[C0:.+]] = arith.constant 0 : index
//   CHECK-DAG:   %[[TX:.+]] = gpu.thread_id x
//   CHECK-DAG:   %[[TY:.+]] = gpu.thread_id y
//       CHECK:   %[[TFLAT:.+]] = affine.linearize_index disjoint [%[[TY]], %[[TX]]] by (2, 64)
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]
//       CHECK:   scf.for %[[I:.+]] = %[[C0]] to %[[C512]] step %[[C128]] {
//       CHECK:     %[[LINID:.+]] = affine.apply affine_map<(d0)[s0] -> (d0 + s0)>(%[[I]])[%[[TFLAT]]]
//       CHECK:     %[[DELIN:.+]]:3 = affine.delinearize_index %[[LINID]] into (16, 8, 4) : index
//       CHECK:     memref.store {{.*}}[%[[DELIN]]#0, %[[DELIN]]#1, %[[DELIN]]#2]
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]

// -----

#translation_info = #iree_codegen.translation_info<pipeline = #iree_gpu.pipeline<TileAndFuse> workgroup_size = [7, 1, 1] subgroup_size = 32>

func.func @distribute_thread_forall_small_workgroup(%out : memref<?xi32>)
    attributes {translation_info = #translation_info} {
  %c0 = arith.constant 0 : i32
  scf.forall (%arg0) in (7) {
    memref.store %c0, %out[%arg0] : memref<?xi32>
  } {mapping = [#gpu.thread<linear_dim_0>]}
  return
}

// CHECK-LABEL: func @distribute_thread_forall_small_workgroup
//       CHECK:   %[[TX:.+]] = gpu.thread_id x
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]
//       CHECK:   memref.store {{.*}}[%[[TX]]]
//       CHECK:   gpu.barrier memfence [#gpu.address_space<workgroup>]

// -----

// Verify that a thread-mapped forall nested inside a warp-mapped forall uses
// warp-local (lane) IDs instead of global thread IDs.
//
// With workgroup_size=[256,1,1] and subgroup_size=64, there are 4 warps.
// The outer warp forall distributes across 4 warps.  The inner thread forall
// has 8 iterations and should use lane IDs (0-63) with step=64, so that in
// each warp, lanes 0-7 execute the body independently.
//
// BUG (before fix): the inner loop used global thread ID (0-255) with step=256,
// meaning only global threads 0-7 (all in warp 0) would ever execute.

#translation_info_nested = #iree_codegen.translation_info<pipeline = #iree_gpu.pipeline<TileAndFuse> workgroup_size = [256, 1, 1] subgroup_size = 64>

func.func @distribute_thread_in_warp_forall(%out : memref<32xi32, #gpu.address_space<workgroup>>)
    attributes {translation_info = #translation_info_nested} {
  %c0 = arith.constant 0 : i32
  scf.forall (%warp_id) in (4) {
    scf.forall (%tid) in (8) {
      %idx = affine.apply affine_map<(d0, d1) -> (d0 * 8 + d1)>(%warp_id, %tid)
      memref.store %c0, %out[%idx] : memref<32xi32, #gpu.address_space<workgroup>>
    } {mapping = [#gpu.thread<linear_dim_0>]}
  } {mapping = [#gpu.warp<linear_dim_0>]}
  return
}

// The inner thread loop should use lane ID (subgroup-local) with step=64,
// NOT global thread ID with step=256.
// CHECK-LABEL: func @distribute_thread_in_warp_forall
//   CHECK-DAG:   %[[C64:.+]] = arith.constant 64 : index
//   CHECK-DAG:   %[[C8:.+]] = arith.constant 8 : index
//       CHECK:   %[[TX:.+]] = gpu.thread_id x
//       CHECK:   %[[WARPSPLIT:.+]]:2 = affine.delinearize_index %[[TX]] into (4, 64)
//       CHECK:   scf.for %[[IV:.+]] = %[[WARPSPLIT]]#1 to %[[C8]] step %[[C64]]
//       CHECK:     memref.store

// -----

// Similar test but with fewer threads than the subgroup size and a
// multi-dimensional warp forall.  Thread forall has 3 iterations nested inside
// a 2D warp forall (2x2 = 4 warps).

#translation_info_nested2 = #iree_codegen.translation_info<pipeline = #iree_gpu.pipeline<TileAndFuse> workgroup_size = [256, 1, 1] subgroup_size = 64>

func.func @distribute_thread_in_2d_warp_forall(%out : memref<4x3xi32, #gpu.address_space<workgroup>>)
    attributes {translation_info = #translation_info_nested2} {
  %c0 = arith.constant 0 : i32
  scf.forall (%wy, %wx) in (2, 2) {
    scf.forall (%tid) in (3) {
      memref.store %c0, %out[%wy, %tid] : memref<4x3xi32, #gpu.address_space<workgroup>>
    } {mapping = [#gpu.thread<linear_dim_0>]}
  } {mapping = [#gpu.warp<linear_dim_1>, #gpu.warp<linear_dim_0>]}
  return
}

// CHECK-LABEL: func @distribute_thread_in_2d_warp_forall
//   CHECK-DAG:   %[[C64:.+]] = arith.constant 64 : index
//   CHECK-DAG:   %[[C3:.+]] = arith.constant 3 : index
//       CHECK:   %[[TX:.+]] = gpu.thread_id x
//       CHECK:   %[[WARPSPLIT:.+]]:2 = affine.delinearize_index %[[TX]] into (4, 64)
//       CHECK:   scf.for {{.*}} to %[[C3]] step %[[C64]]
