// Copyright 2025 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef IREE_PREPROCESSING_TRANSFORM_EXTENSIONS_PYTHON_BINDING
#define IREE_PREPROCESSING_TRANSFORM_EXTENSIONS_PYTHON_BINDING

include "iree/compiler/Preprocessing/TransformExtensions/PreprocessingExtensionsOps.td"

#endif // IREE_PREPROCESSING_TRANSFORM_EXTENSIONS_PYTHON_BINDING
