// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "iree/hal/replay/help.h"

static const char kIreeHalReplayCaptureUsage[] =
    "Runs a compiled IREE module and can record the HAL work as an\n"
    ".ireereplay reproducer.\n"
    "\n"
    "Replay capture wraps the resolved HAL device group after normal "
    "--device=\n"
    "selection. All devices in that group share one recorder, so multi-device\n"
    "HAL calls are emitted into one host-call-ordered stream. Device-visible\n"
    "ordering is still the recorded semaphore, event, command-buffer, and\n"
    "barrier graph; replay does not infer FIFO ordering from host record "
    "order.\n"
    "\n"
    "Capture flags:\n"
    "  --device_replay_output=path.ireereplay\n"
    "      Writes a HAL replay stream. The recorder is closed after the "
    "tool's\n"
    "      HAL work completes so the file header contains the final length.\n"
    "  --device_replay_file_policy=reference|fail\n"
    "      Controls imported fd-backed HAL files such as parameter archives.\n"
    "      reference records the external path and validation metadata "
    "instead\n"
    "      of copying the file bytes. fail rejects fd-backed files so the\n"
    "      capture cannot accidentally depend on external storage.\n"
    "  --device_replay_file_validation=identity|digest\n"
    "      Validation for referenced fd-backed files. identity is the default\n"
    "      and does not read file contents. digest is opt-in and reads every "
    "byte\n"
    "      of each referenced file during capture and replay.\n"
    "  --agents_md\n"
    "      Prints a Markdown guide covering capture, API embedding, replay,\n"
    "      benchmarking, dumps, and common diagnostics.\n"
    "\n"
    "Tool capture example:\n"
    "  iree-run-module --device=local-sync --module=model.vmfb \\\n"
    "      --function=main --input=@inputs.txt \\\n"
    "      --device_replay_output=/tmp/model.ireereplay \\\n"
    "      --device_replay_file_policy=reference\n"
    "\n"
    "Replay and inspect:\n"
    "  iree-run-replay --device=local-sync /tmp/model.ireereplay\n"
    "  iree-benchmark-replay --device=local-sync --benchmark_min_time=20x \\\n"
    "      /tmp/model.ireereplay\n"
    "  iree-dump-replay --format=jsonl /tmp/model.ireereplay\n";

static const char kIreeHalReplayRunUsage[] =
    "Executes an IREE HAL replay file against one or more HAL devices.\n"
    "\n"
    "The replay executor reconstructs the recorded HAL resource graph and\n"
    "reissues supported HAL operations against a freshly-created device "
    "group.\n"
    "Execution follows the recorded host-call sequence deterministically, "
    "while\n"
    "the device work itself is ordered by the captured semaphore, event,\n"
    "command-buffer, and barrier dependencies. Select the target topology "
    "with\n"
    "--device= just like iree-run-module.\n"
    "\n"
    "Usage:\n"
    "  iree-run-replay [options] <capture.ireereplay>\n"
    "\n"
    "Important flags:\n"
    "  --device=URI\n"
    "      Target HAL device URI. Repeat or use the existing device flag "
    "shape\n"
    "      for multi-device targets supported by this build.\n"
    "  --replay_file_remap=captured_prefix=replay_prefix\n"
    "      Remaps referenced external file paths before replay opens them. "
    "The\n"
    "      replay still validates the captured file identity after remapping.\n"
    "      Repeat the flag for multiple roots.\n"
    "  --replay_executable_substitution=EXECUTABLE_ID=PATH\n"
    "  --replay_executable_substitution=EXECUTABLE_ID@FORMAT=PATH\n"
    "      Replaces a captured executable payload. Use iree-dump-replay to "
    "find\n"
    "      executable object ids; dispatch records reference those ids. The\n"
    "      replay validates export counts and reflected ABI shape before "
    "using\n"
    "      the replacement.\n"
    "  --device_profiling_mode=...\n"
    "  --device_profiling_output=path.ireeprof\n"
    "      Captures HAL-native profiling for the replay execution. Tool setup "
    "and\n"
    "      teardown are outside the profiling window; captured setup "
    "operations\n"
    "      inside the replay stream remain part of the replay workload.\n"
    "  --agents_md\n"
    "      Prints a Markdown guide covering capture and replay workflows.\n"
    "\n"
    "Examples:\n"
    "  iree-run-replay --device=local-sync /tmp/model.ireereplay\n"
    "  iree-run-replay --device=local-sync \\\n"
    "      --replay_file_remap=/mnt/train=/mnt/replay \\\n"
    "      /tmp/model.ireereplay\n";

static const char kIreeHalReplayBenchmarkUsage[] =
    "Benchmarks deterministic execution of an IREE HAL replay file.\n"
    "\n"
    "Each Google Benchmark iteration replays the complete captured HAL stream\n"
    "against the selected device group. Profiling flushes are performed "
    "outside\n"
    "the timed region, so --device_profiling_output captures the useful "
    "replay\n"
    "work without charging the benchmark iteration for profile serialization.\n"
    "\n"
    "Usage:\n"
    "  iree-benchmark-replay [benchmark options] [replay options]\n"
    "      <capture.ireereplay>\n"
    "\n"
    "Important flags:\n"
    "  --device=URI\n"
    "      Target HAL device URI, matching iree-benchmark-module.\n"
    "  --replay_file_remap=captured_prefix=replay_prefix\n"
    "      Remaps referenced external file paths before strict identity\n"
    "      validation. Repeat the flag for multiple roots.\n"
    "  --replay_executable_substitution=EXECUTABLE_ID=PATH\n"
    "  --replay_executable_substitution=EXECUTABLE_ID@FORMAT=PATH\n"
    "      Replaces captured executable payloads for kernel iteration. The "
    "same\n"
    "      syntax and ABI validation as iree-run-replay applies.\n"
    "  --benchmark_min_time=20x\n"
    "      Useful for fixed-iteration replay benchmarking. Google Benchmark\n"
    "      flags are accepted by this tool.\n"
    "  --device_profiling_mode=queue-events,host-execution\n"
    "  --device_profiling_output=path.ireeprof\n"
    "      Captures HAL profiling for benchmarked replay iterations.\n"
    "  --agents_md\n"
    "      Prints a Markdown guide covering capture and replay workflows.\n"
    "\n"
    "Examples:\n"
    "  iree-benchmark-replay --device=local-sync --benchmark_min_time=20x \\\n"
    "      /tmp/model.ireereplay\n"
    "  iree-benchmark-replay --device=amdgpu --benchmark_min_time=50x \\\n"
    "      --device_profiling_mode=queue-events,device-queue-events \\\n"
    "      --device_profiling_output=/tmp/model-replay.ireeprof \\\n"
    "      /tmp/model.ireereplay\n";

static const char kIreeHalReplayDumpUsage[] =
    "Dumps information from an IREE HAL replay file.\n"
    "\n"
    "The dumper validates the replay container and emits projections without\n"
    "materializing large payload bytes. Blob data and embedded payloads are\n"
    "reported as byte ranges in the original .ireereplay file so JSONL and\n"
    "the C projection can reference the capture directly.\n"
    "\n"
    "Usage:\n"
    "  iree-dump-replay [--format=text|jsonl|c] <capture.ireereplay>\n"
    "\n"
    "Formats:\n"
    "  text\n"
    "      Human-readable record stream for quick inspection.\n"
    "  jsonl\n"
    "      One JSON object per line for jq and automation. Payload bytes are\n"
    "      represented as replay-file ranges.\n"
    "  c\n"
    "      Reserved for the C reproducer projection. The flag is accepted so\n"
    "      scripts can probe support, but current builds return "
    "UNIMPLEMENTED.\n"
    "\n"
    "Important flags:\n"
    "  --agents_md\n"
    "      Prints a Markdown guide covering capture and replay workflows.\n"
    "\n"
    "Examples:\n"
    "  iree-dump-replay --format=text /tmp/model.ireereplay\n"
    "  iree-dump-replay --format=jsonl /tmp/model.ireereplay | \\\n"
    "      jq 'select(.kind==\"operation\" and "
    ".operation==\"device.queue_execute\")'\n";

const char* iree_hal_replay_capture_usage_text(void) {
  return kIreeHalReplayCaptureUsage;
}

const char* iree_hal_replay_run_usage_text(void) {
  return kIreeHalReplayRunUsage;
}

const char* iree_hal_replay_benchmark_usage_text(void) {
  return kIreeHalReplayBenchmarkUsage;
}

const char* iree_hal_replay_dump_usage_text(void) {
  return kIreeHalReplayDumpUsage;
}

static void iree_hal_replay_print_agent_markdown_overview(FILE* file) {
  fputs(
      "# IREE HAL Replay Capture And Tools\n"
      "\n"
      "Use HAL replay when you need a reproducible HAL-level workload from an\n"
      "IREE application. A capture records the HAL resource graph, byte "
      "payloads\n"
      "that the host writes through visible HAL operations, executable "
      "payloads,\n"
      "external file references, command buffers, queue operations, and\n"
      "synchronization edges into one `.ireereplay` file.\n"
      "\n"
      "Replay is separate from profiling. `.ireereplay` says what HAL work to\n"
      "run; `.ireeprof` says what happened while a run executed. A normal\n"
      "dogfood loop captures once, replays many times, and optionally "
      "captures\n"
      "`.ireeprof` bundles from `iree-benchmark-replay`.\n"
      "\n"
      "The capture is intentionally tied to `iree_hal_device_group_t`. A "
      "device\n"
      "group preserves topology and gives the recorder one place to wrap "
      "every\n"
      "device in the group. Multi-threaded host calls receive monotonically\n"
      "ordered record sequence numbers, making replay deterministic even when "
      "it\n"
      "runs less parallel than the original application.\n"
      "\n",
      file);
}

static void iree_hal_replay_print_agent_markdown_capture(FILE* file) {
  fputs(
      "## Capture With IREE Tools\n"
      "\n"
      "`iree-run-module` and `iree-benchmark-module` can record the HAL work\n"
      "they issue. Add `--device_replay_output` to write a capture and keep "
      "the\n"
      "usual module, function, device, parameter, and input flags unchanged.\n"
      "\n"
      "```bash\n"
      "iree-run-module --device=local-sync --module=model.vmfb \\\n"
      "  --function=main --input=@inputs.txt \\\n"
      "  --device_replay_output=/tmp/model.ireereplay \\\n"
      "  --device_replay_file_policy=reference\n"
      "```\n"
      "\n"
      "Use `--device_replay_file_policy=reference` for parameter archives and\n"
      "other large stable files. FD-backed HAL files are recorded by path and\n"
      "validation metadata, so a 40 GB `.irpa` file does not get copied into\n"
      "every capture. Host-allocation-backed HAL files have no durable "
      "external\n"
      "identity and are embedded inline.\n"
      "\n"
      "The default file validation mode is `identity`. It records length,\n"
      "device, inode, and modification time metadata and does not scan "
      "external\n"
      "file contents. Use `--device_replay_file_validation=digest` only when\n"
      "the referenced files will be copied or staged to another filesystem "
      "and\n"
      "you accept a full byte scan of each referenced file during capture and\n"
      "again during replay.\n"
      "\n"
      "Use `--device_replay_file_policy=fail` when you require the capture "
      "step\n"
      "to reject every fd-backed external HAL file. That is useful in tests "
      "that\n"
      "must prove they are not depending on external model weights or "
      "datasets.\n"
      "\n"
      "`iree-benchmark-module` records the benchmark registration/run path. "
      "The\n"
      "replay recorder is closed after benchmark execution, so the output file "
      "is\n"
      "complete when the tool exits.\n"
      "\n",
      file);
}

static void iree_hal_replay_print_agent_markdown_api(FILE* file) {
  fputs(
      "## Capture From An Embedding Application\n"
      "\n"
      "Applications that come through the HAL API should wrap the retained "
      "device\n"
      "group they already use to construct the HAL module or to issue direct "
      "HAL\n"
      "work. The wrapped group has the same topology order as the source "
      "group.\n"
      "\n"
      "```c\n"
      "iree_io_file_handle_t* file_handle = NULL;\n"
      "IREE_RETURN_IF_ERROR(iree_io_file_handle_create(\n"
      "    IREE_IO_FILE_MODE_WRITE | IREE_IO_FILE_MODE_SEQUENTIAL_SCAN |\n"
      "        IREE_IO_FILE_MODE_SHARE_READ,\n"
      "    IREE_SV(\"/tmp/model.ireereplay\"), /*initial_size=*/0,\n"
      "    host_allocator, &file_handle));\n"
      "\n"
      "iree_hal_replay_recorder_options_t options =\n"
      "    iree_hal_replay_recorder_options_default();\n"
      "options.external_file_policy =\n"
      "    IREE_HAL_REPLAY_RECORDER_EXTERNAL_FILE_POLICY_REFERENCE;\n"
      "\n"
      "iree_hal_replay_recorder_t* recorder = NULL;\n"
      "IREE_RETURN_IF_ERROR(iree_hal_replay_recorder_create(\n"
      "    file_handle, &options, host_allocator, &recorder));\n"
      "iree_io_file_handle_release(file_handle);\n"
      "\n"
      "iree_hal_device_group_t* replay_group = NULL;\n"
      "IREE_RETURN_IF_ERROR(iree_hal_replay_wrap_device_group(\n"
      "    recorder, base_group, host_allocator, &replay_group));\n"
      "\n"
      "/* Run the application using replay_group wherever the HAL device "
      "group\n"
      "   would normally be used. */\n"
      "\n"
      "iree_hal_device_group_release(replay_group);\n"
      "iree_status_t close_status = iree_hal_replay_recorder_close(recorder);\n"
      "iree_hal_replay_recorder_release(recorder);\n"
      "IREE_RETURN_IF_ERROR(close_status);\n"
      "```\n"
      "\n"
      "Close the recorder after all HAL work and host-visible writes have "
      "reached\n"
      "their HAL boundaries. Closing writes the final file length and reports "
      "any\n"
      "terminal recorder failure instead of silently producing a partial "
      "replay.\n"
      "\n",
      file);
}

static void iree_hal_replay_print_agent_markdown_replay(FILE* file) {
  fputs(
      "## Run And Benchmark A Capture\n"
      "\n"
      "Run a replay once with `iree-run-replay`:\n"
      "\n"
      "```bash\n"
      "iree-run-replay --device=local-sync /tmp/model.ireereplay\n"
      "```\n"
      "\n"
      "Benchmark the same HAL stream with Google Benchmark controls:\n"
      "\n"
      "```bash\n"
      "iree-benchmark-replay --device=local-sync --benchmark_min_time=20x \\\n"
      "  /tmp/model.ireereplay\n"
      "```\n"
      "\n"
      "Capture profiling while benchmarking replayed work:\n"
      "\n"
      "```bash\n"
      "iree-benchmark-replay --device=amdgpu --benchmark_min_time=50x \\\n"
      "  --device_profiling_mode=queue-events,device-queue-events \\\n"
      "  --device_profiling_output=/tmp/model-replay.ireeprof \\\n"
      "  /tmp/model.ireereplay\n"
      "```\n"
      "\n"
      "If the original capture referenced parameter files from a different "
      "mount\n"
      "root, remap the captured prefix before replay opens files:\n"
      "\n"
      "```bash\n"
      "iree-run-replay --device=local-sync \\\n"
      "  --replay_file_remap=/mnt/capture=/mnt/replay \\\n"
      "  /tmp/model.ireereplay\n"
      "```\n"
      "\n"
      "The remapped file must still match the recorded identity. A mismatch is "
      "a\n"
      "hard failure because otherwise the replay could silently benchmark a\n"
      "different model or dataset.\n"
      "\n"
      "To iterate on generated kernels while preserving the captured HAL "
      "workload,\n"
      "substitute an executable by captured executable object id:\n"
      "\n"
      "```bash\n"
      "iree-dump-replay --format=text /tmp/model.ireereplay | grep "
      "executable\n"
      "iree-run-replay --device=amdgpu \\\n"
      "  --replay_executable_substitution=4=/tmp/new-kernel.hsaco \\\n"
      "  /tmp/model.ireereplay\n"
      "```\n"
      "\n"
      "If the target executable cache can infer formats, omit `@FORMAT` and "
      "pass\n"
      "`EXECUTABLE_ID=PATH`. Substitution is strict: replay prepares the\n"
      "captured and replacement executable, compares export counts, "
      "constants,\n"
      "bindings, workgroup sizes, and reflected parameter layouts, then fails\n"
      "before dispatch when the replacement ABI does not match the capture.\n"
      "\n",
      file);
}

static void iree_hal_replay_print_agent_markdown_dump(FILE* file) {
  fputs(
      "## Inspect A Capture\n"
      "\n"
      "Use text mode for quick inspection:\n"
      "\n"
      "```bash\n"
      "iree-dump-replay --format=text /tmp/model.ireereplay\n"
      "```\n"
      "\n"
      "Use JSONL for queries and agent workflows:\n"
      "\n"
      "```bash\n"
      "iree-dump-replay --format=jsonl /tmp/model.ireereplay | \\\n"
      "  jq 'select(.kind==\"operation\" and "
      ".operation==\"device.queue_execute\")'\n"
      "```\n"
      "\n"
      "JSONL rows carry object ids, operation ids, queue wait/signal lists,\n"
      "buffer binding tables, file references, and replay-file byte ranges. "
      "The\n"
      "dumper does not print raw blob bytes, which keeps large captures "
      "queryable\n"
      "and lets generated projections reference ranges in the original replay\n"
      "file.\n"
      "\n"
      "`--format=c` is reserved for the C reproducer projection. Current "
      "builds\n"
      "return UNIMPLEMENTED for that format instead of emitting a partial C "
      "file.\n"
      "\n",
      file);
}

static void iree_hal_replay_print_agent_markdown_diagnostics(FILE* file) {
  fputs(
      "## Diagnostics And Contracts\n"
      "\n"
      "A useful replay must fail loudly when it cannot reproduce the captured "
      "HAL\n"
      "work. Treat these failures as part of the contract:\n"
      "\n"
      "- Missing or identity-mismatched referenced files mean the replay may "
      "be\n"
      "  pointing at the wrong parameter archive. Fix the file path with\n"
      "  `--replay_file_remap` or restore the referenced file before "
      "replaying.\n"
      "- Persistent host write maps without an observable flush or unmap "
      "boundary\n"
      "  are rejected because replay cannot see the final byte contents.\n"
      "- Host calls, channels, collectives, opaque external handles, and "
      "other\n"
      "  unsupported operations should remain visible in dumps and fail in "
      "strict\n"
      "  execution instead of being skipped.\n"
      "- Device topology matters. Use a replay target whose device count and\n"
      "  capabilities match the captured HAL workload, then use profiling "
      "output\n"
      "  to compare performance on alternate devices.\n"
      "\n"
      "When debugging a capture, keep the `.ireereplay` and any external "
      "parameter\n"
      "files together, dump JSONL first, run once with `iree-run-replay`, "
      "then\n"
      "benchmark with profiling enabled only after the single-run path is "
      "clean.\n",
      file);
}

void iree_hal_replay_print_agent_markdown(FILE* file) {
  iree_hal_replay_print_agent_markdown_overview(file);
  iree_hal_replay_print_agent_markdown_capture(file);
  iree_hal_replay_print_agent_markdown_api(file);
  iree_hal_replay_print_agent_markdown_replay(file);
  iree_hal_replay_print_agent_markdown_dump(file);
  iree_hal_replay_print_agent_markdown_diagnostics(file);
}
