// Copyright 2021 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef IREE_CODEGEN_DIALECT_IREECODEGEN_ATTRIBUTES
#define IREE_CODEGEN_DIALECT_IREECODEGEN_ATTRIBUTES

include "iree/compiler/Codegen/Dialect/IREECodegenDialect.td"
include "iree/compiler/Codegen/Dialect/LoweringConfig.td"


#endif // IREE_CODEGEN_DIALECT_IREECODEGEN_ATTRIBUTES
