# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//build_tools/bazel:build_defs.oss.bzl", "iree_compiler_cc_test")

package(
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

iree_compiler_cc_test(
    name = "QuantizedContractionTest",
    testonly = True,
    srcs = ["QuantizedContractionTest.cpp"],
    deps = [
        "//compiler/src/iree/compiler/Dialect/LinalgExt/IR",
        "//compiler/src/iree/compiler/GlobalOptimization:QuantizedContraction",
        "//compiler/src/iree/testing:gtest_main",
        "@com_google_googletest//:gtest",
        "@llvm-project//llvm:Support",
        "@llvm-project//mlir:ArithDialect",
        "@llvm-project//mlir:FuncDialect",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:LinalgDialect",
        "@llvm-project//mlir:Parser",
    ],
)

iree_compiler_cc_test(
    name = "QuantizationUtilsTest",
    testonly = True,
    srcs = ["QuantizationUtilsTest.cpp"],
    deps = [
        "//compiler/src/iree/compiler/GlobalOptimization:QuantizationUtils",
        "//compiler/src/iree/testing:gtest_main",
        "@com_google_googletest//:gtest",
    ],
)
