# Autogenerated from /home/jmonsalv/develop/dataflow_dependencies/iree/compiler/lit.site.cfg.py.in
# Do not edit!



import sys

config.iree_obj_root = "/home/jmonsalv/develop/dataflow_dependencies/iree/build"
config.lib_dir = "/home/jmonsalv/develop/dataflow_dependencies/iree/build/lib"
config.lib_ext = ".so"
config.python_executable = "/usr/bin/python3"

import lit.llvm
lit.llvm.initialize(lit_config, config)

# Let the main config do the real work
lit_config.load_config(config, "/home/jmonsalv/develop/dataflow_dependencies/iree/compiler/lit.cfg.py")
