// RUN: ${TEST_MODULE_CMD} \
// RUN:   --module_file="${BUILD_RISCV_DIR}/tests/e2e/models/tflite_llvm-cpu_local-task_efficientnet_lite0_int8_2.tflite_module.vmfb" \
// RUN:   --entry_function=main --function_input="1x224x224x3xui8=0" | \
// RUN:   grep "=\[" | tee %t
//
// RUN: ${HOST_TEST_MODULE_CMD} \
// RUN:   --module_file="${BUILD_RISCV_DIR}/tests/e2e/models/tflite_llvm-cpu_local-task_x86_64_efficientnet_lite0_int8_2.tflite_module.vmfb" \
// RUN:   --entry_function=main --function_input="1x224x224x3xui8=0" | \
// RUN:   grep "=\[" | tee %t.x86_64
//
// Compare numerical results.
// RUN: python ${IREE_ROOT_DIR}/build_tools/testing/compare_run_module_output.py \
// RUN:   --tol=0 %t %t.x86_64
