# Copyright 2020 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

package(
    default_visibility = ["//visibility:public"],
    features = ["layering_check"],
    licenses = ["notice"],  # Apache 2.0
)

cc_library(
    name = "tf_strings",
    deps = [
        "//iree_tf_compiler/dialect/tf_strings/conversion",
        "//iree_tf_compiler/dialect/tf_strings/ir",
    ],
)
