// Copyright 2021 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "iree/vm/shims.h"

IREE_VM_ABI_DEFINE_SHIM(irii, v);
IREE_VM_ABI_DEFINE_SHIM(r, i);
IREE_VM_ABI_DEFINE_SHIM(r, ii);
IREE_VM_ABI_DEFINE_SHIM(r, iii);
IREE_VM_ABI_DEFINE_SHIM(r, iiii);
IREE_VM_ABI_DEFINE_SHIM(r, r);
IREE_VM_ABI_DEFINE_SHIM(r, v);
IREE_VM_ABI_DEFINE_SHIM(rCiD, i);
IREE_VM_ABI_DEFINE_SHIM(rCrD, v);
IREE_VM_ABI_DEFINE_SHIM(ri, i);
IREE_VM_ABI_DEFINE_SHIM(ri, r);
IREE_VM_ABI_DEFINE_SHIM(ri, v);
IREE_VM_ABI_DEFINE_SHIM(riCiD, r);
IREE_VM_ABI_DEFINE_SHIM(riiCiD, r);
IREE_VM_ABI_DEFINE_SHIM(riCiiiD, r);
IREE_VM_ABI_DEFINE_SHIM(riCrD, r);
IREE_VM_ABI_DEFINE_SHIM(rii, i);
IREE_VM_ABI_DEFINE_SHIM(rii, r);
IREE_VM_ABI_DEFINE_SHIM(riii, r);
IREE_VM_ABI_DEFINE_SHIM(riii, v);
IREE_VM_ABI_DEFINE_SHIM(riirii, r);
IREE_VM_ABI_DEFINE_SHIM(riiirii, r);
IREE_VM_ABI_DEFINE_SHIM(rrrCrD, r);
IREE_VM_ABI_DEFINE_SHIM(ririi, v);
IREE_VM_ABI_DEFINE_SHIM(rr, i);
IREE_VM_ABI_DEFINE_SHIM(rr, r);
IREE_VM_ABI_DEFINE_SHIM(rr, v);
IREE_VM_ABI_DEFINE_SHIM(rr, ii);
IREE_VM_ABI_DEFINE_SHIM(rrr, ii);
IREE_VM_ABI_DEFINE_SHIM(rrCiriiD, r);
IREE_VM_ABI_DEFINE_SHIM(rriCiD, v);
IREE_VM_ABI_DEFINE_SHIM(rriCiriiD, v);
IREE_VM_ABI_DEFINE_SHIM(rriii, v);
IREE_VM_ABI_DEFINE_SHIM(rriiii, v);
IREE_VM_ABI_DEFINE_SHIM(rrirCiD, v);
IREE_VM_ABI_DEFINE_SHIM(rriri, v);
IREE_VM_ABI_DEFINE_SHIM(rririi, v);
IREE_VM_ABI_DEFINE_SHIM(v, i);
IREE_VM_ABI_DEFINE_SHIM(v, r);
IREE_VM_ABI_DEFINE_SHIM(v, v);
