# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

"""Bazel repository rule that downloads wasi-sdk for the host platform.

wasi-sdk provides clang + lld + wasi-libc (musl) + libc++ + compiler-rt,
packaged as a self-contained toolchain for WebAssembly targets. We use it
as THE wasm toolchain for both runtime builds (wasm32-unknown-unknown with
our freestanding libc) and test builds (wasm32-wasi with full C++ stdlib).

The downloaded SDK is exposed as a Bazel external repository (@wasi_sdk)
with executable targets for each tool.
"""

load("//build_tools/wasm:wasi_sdk_version.bzl", "WASI_SDK_SHA256", "WASI_SDK_TAG", "WASI_SDK_URL_TEMPLATE", "WASI_SDK_VERSION")

# Starlark source for prebuilt_tool.bzl, written into the downloaded repo.
# This rule wraps a pre-built binary as an executable Bazel target, which
# is required because cc_tool's `src` attribute demands `executable = True`
# and plain files from exports_files don't satisfy that constraint.
_PREBUILT_TOOL_BZL = """\
\"\"\"Rule for exposing pre-built binaries as executable Bazel targets.\"\"\"

def _prebuilt_tool_impl(ctx):
    out = ctx.actions.declare_file(ctx.label.name)
    ctx.actions.symlink(
        output = out,
        target_file = ctx.file.src,
        is_executable = True,
    )
    runfiles = ctx.runfiles(files = ctx.files.data + [ctx.file.src])
    return [DefaultInfo(
        executable = out,
        files = depset([out]),
        runfiles = runfiles,
    )]

prebuilt_tool = rule(
    implementation = _prebuilt_tool_impl,
    executable = True,
    attrs = {
        "src": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The pre-built binary file.",
        ),
        "data": attr.label_list(
            allow_files = True,
            doc = "Additional files the tool needs at runtime.",
        ),
    },
    doc = "Wraps a pre-built binary as an executable Bazel target.",
)
"""

# BUILD.bazel template for the downloaded wasi-sdk repository.
_BUILD_TEMPLATE = """\
# AUTO-GENERATED by wasi_sdk_repo.bzl — do not edit.

load(":prebuilt_tool.bzl", "prebuilt_tool")

package(default_visibility = ["//visibility:public"])

exports_files(glob(["bin/*"]))

#--- Freestanding tools (no sysroot, for wasm32-unknown-unknown) ---#

prebuilt_tool(
    name = "clang",
    src = "bin/clang",
    data = glob(["lib/**"]),
)

prebuilt_tool(
    name = "lld",
    src = "bin/lld",
)

prebuilt_tool(
    name = "llvm-ar",
    src = "bin/llvm-ar",
)

prebuilt_tool(
    name = "llvm-objcopy",
    src = "bin/llvm-objcopy",
)

prebuilt_tool(
    name = "llvm-objdump",
    src = "bin/llvm-objdump",
)

prebuilt_tool(
    name = "llvm-strip",
    src = "bin/llvm-strip",
)

#--- Sysroot filegroup ---#

filegroup(
    name = "sysroot",
    srcs = glob(["share/wasi-sysroot/**"]),
)

# Clang resource directory (builtins headers and compiler-rt libraries).
# Needed as explicit inputs when using -resource-dir to override the
# default path that clang computes from its executable location.
filegroup(
    name = "clang_resources",
    srcs = glob(["lib/clang/**"]),
)
"""

def _detect_host_platform(repository_ctx):
    """Returns (arch, os) matching wasi-sdk release naming."""
    os_name = repository_ctx.os.name.lower()
    arch = repository_ctx.os.arch

    if "linux" in os_name:
        os_key = "linux"
    elif "mac" in os_name or "darwin" in os_name:
        os_key = "macos"
    else:
        fail("wasi-sdk: unsupported host OS: {}".format(os_name))

    if arch in ("amd64", "x86_64"):
        arch_key = "x86_64"
    elif arch in ("aarch64", "arm64"):
        arch_key = "arm64"
    else:
        fail("wasi-sdk: unsupported host architecture: {}".format(arch))

    return arch_key, os_key

def _wasi_sdk_repo_impl(repository_ctx):
    arch, os = _detect_host_platform(repository_ctx)
    platform_key = "{}-{}".format(arch, os)

    sha256 = WASI_SDK_SHA256.get(platform_key, "")
    if not sha256:
        fail("wasi-sdk: no SHA-256 hash for platform {}".format(platform_key))

    url = WASI_SDK_URL_TEMPLATE.format(
        tag = WASI_SDK_TAG,
        version = WASI_SDK_VERSION,
        arch = arch,
        os = os,
    )
    strip_prefix = "wasi-sdk-{}-{}-{}".format(WASI_SDK_VERSION, arch, os)

    repository_ctx.download_and_extract(
        url = url,
        sha256 = sha256,
        stripPrefix = strip_prefix,
    )

    repository_ctx.file("prebuilt_tool.bzl", _PREBUILT_TOOL_BZL)
    repository_ctx.file("BUILD.bazel", _BUILD_TEMPLATE)

    # Detect the clang resource directory version (e.g., "21" for LLVM 21.x).
    # The resource dir contains builtins headers (stddef.h, stdarg.h, etc.)
    # and compiler-rt libraries (libclang_rt.builtins-wasm32.a).
    result = repository_ctx.execute(["ls", "lib/clang/"])
    clang_version = result.stdout.strip()
    if not clang_version or "\n" in clang_version:
        fail("Expected exactly one clang version directory under lib/clang/, got: {}".format(
            repr(result.stdout),
        ))

    # Write execroot-relative paths for use in cc_args.
    # repository_ctx.name is the canonical name (including the Bzlmod prefix),
    # so the execroot path is always "external/<canonical_name>/...".
    sysroot_path = "external/{}/share/wasi-sysroot".format(repository_ctx.name)
    resource_dir = "external/{}/lib/clang/{}".format(repository_ctx.name, clang_version)
    repository_ctx.file("paths.bzl", """\
\"\"\"Execroot-relative paths for the wasi-sdk sysroot and clang resource directory.\"\"\"
WASI_SYSROOT_PATH = "{sysroot}"
WASI_RESOURCE_DIR = "{resource_dir}"
""".format(sysroot = sysroot_path, resource_dir = resource_dir))

wasi_sdk_repo = repository_rule(
    implementation = _wasi_sdk_repo_impl,
    doc = "Downloads wasi-sdk for the host platform and exposes its tools.",
)
