"""Minimal set of aliases to redirect mlir-hlo dependencies to their location in TF."""

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

alias(
    name = "hlo",
    actual = "@org_tensorflow//tensorflow/compiler/mlir/hlo",
)

alias(
    name = "lhlo",
    actual = "@org_tensorflow//tensorflow/compiler/mlir/hlo:lhlo",
)
