# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI - Linux x64 clang ASan

on:
  workflow_call:
  workflow_dispatch:

jobs:
  linux_x64_clang_asan:
    runs-on: azure-linux-scale
    container: ghcr.io/iree-org/cpubuilder_ubuntu_jammy@sha256:78a558b999b230f7e1da376639e14b44f095f30f1777d6a272ba48c0bbdd4ccb
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
      - name: Install Python requirements
        run: python3 -m pip install -r ./runtime/bindings/python/iree/runtime/build_requirements.txt
      - name: Build and test with ASan
        env:
          # Use a modern clang explicitly.
          CC: clang-19
          CXX: clang++-19
          SCCACHE_AZURE_CONNECTION_STRING: "${{ secrets.AZURE_CCACHE_CONNECTION_STRING }}"
          SCCACHE_AZURE_BLOB_CONTAINER: ccache-container
          SCCACHE_CACHE_ZSTD_LEVEL: 10
          SCCACHE_AZURE_KEY_PREFIX: "ci_linux_x64_clang_asan"
        run: |
          source build_tools/cmake/setup_sccache.sh
          ./build_tools/cmake/build_and_test_asan.sh
          sccache --show-stats

      # Alerting on failure is the responsibility of the calling job.
